Added ./configure option --disable-python.
git-svn-id: http://libmpsse.googlecode.com/svn/trunk@99 40ca79c6-6fb9-c882-56b7-fc9d6d09e2cd

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -600,6 +600,7 @@ SONAME
 PYLIB
 PYDEV
 SWIG
+BUILD
 LIBOBJS
 EGREP
 GREP
@@ -652,6 +653,7 @@ SHELL'
 ac_subst_files=''
 ac_user_opts='
 enable_option_checking
+enable_python
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1267,6 +1269,12 @@ if test -n "$ac_init_help"; then
      short | recursive ) echo "Configuration of libmpsse 1.2:";;
    esac
   cat <<\_ACEOF
+
+Optional Features:
+  --disable-option-checking  ignore unrecognized --enable/--with options
+  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
+  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --disable-python        Do not build Python wrappers
 
 Some influential environment variables:
   CC          C compiler command
@@ -2115,6 +2123,18 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
+
+
+# Check whether --enable-python was given.
+if test "${enable_python+set}" = set; then :
+  enableval=$enable_python;
+fi
+
+if test "x$enable_python" != "xno"; then :
+  BUILD="swig"
+else
+  BUILD=""
+fi
 
 
 
@@ -3490,23 +3510,25 @@ fi
 done
 
 
-if ! test $SWIG
+if test $BUILD
 then
-	SWIG="$(which swig)"
-fi
+	if ! test $SWIG
+	then
+		SWIG="$(which swig)"
+	fi
 
-if ! test $SWIG
-then
-	echo "error: could not locate swig"
-	exit 1
-fi
+	if ! test $SWIG
+	then
+		echo "error: could not locate swig"
+		exit 1
+	fi
 
-if ! test $PYDEV
-then
-	PYDEV="/usr/include/python$(python --version 2>&1 | awk '{print $2}' | cut -d'.' -f1,2)"
-fi
+	if ! test $PYDEV
+	then
+		PYDEV="/usr/include/python$(python --version 2>&1 | awk '{print $2}' | cut -d'.' -f1,2)"
+	fi
 
-for ac_header in $PYDEV/Python.h
+	for ac_header in $PYDEV/Python.h
 do :
   as_ac_Header=`$as_echo "ac_cv_header_$ac_header" | $as_tr_sh`
 ac_fn_c_check_header_mongrel "$LINENO" "$ac_header" "$as_ac_Header" "$ac_includes_default"
@@ -3523,18 +3545,19 @@ fi
 done
 
 
-if ! test $PYLIB
-then
-		echo "import sys" > pylib.py
-	echo "for path in sys.path: print path" >> pylib.py
-	PYLIB="$(python pylib.py | grep -e '-packages$' | head -1)"
-	rm -f pylib.py
-fi
+	if ! test $PYLIB
+	then
+				echo "import sys" > pylib.py
+		echo "for path in sys.path: print path" >> pylib.py
+		PYLIB="$(python pylib.py | grep -e '-packages$' | head -1)"
+		rm -f pylib.py
+	fi
 
-if ! test -d $PYLIB
-then
-	echo "error: could not locate python library path"
-	exit 1
+	if ! test -d $PYLIB
+	then
+		echo "error: could not locate python library path"
+		exit 1
+	fi
 fi
 
 if test "$(uname)" == "Darwin"
@@ -3547,6 +3570,8 @@ else
 fi
 
 cp confdefs.h config.h
+
+BUILD=$BUILD
 
 SWIG=$SWIG
 
